version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-revinate
            source /usr/local/share/virtualenvs/tap-revinate/bin/activate
            uv pip install -U pip setuptools
            uv pip install .
      - run:
         name: 'pylint'
         command: |
            source /usr/local/share/virtualenvs/tap-revinate/bin/activate
            uv pip install pylint
            pylint tap_revinate -d missing-docstring,dangerous-default-value,logging-format-interpolation,broad-except,consider-using-f-string,too-many-locals,too-many-branches,too-many-statements,invalid-name,redefined-outer-name,consider-using-sys-exit
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
